module.exports = [
  {
    name: "Egg Avocado Toast",
    price: "13.90",
    img: "https://i.imgur.com/1uIJ4vl.jpg",
    description:
      "Freshly sliced avocados atop toasty multigrain bread with drizzle of honey and a hint of lime, topped with fried eggs",
    category: "All Day Breakfast",
    tags: "Classic",
  },
  {
    name: "Bacon Ham-Egg Sandwich",
    price: "13.90",
    img: "https://i.imgur.com/JqZgxQg.jpg",
    description:
      "Pan-fried bacon with chilled ham and freshly poached eggs sandwiched with sourdough slices",
    category: "All Day Breakfast",
  },
  {
    name: "BLT Sandwich",
    price: "13.90",
    img: "https://i.imgur.com/EWHLpgq.jpg",
    description:
      "Your standard bacon, lettuce and tomato combination, served with toasted sourdough slices",
    category: "All Day Breakfast",
  },
  {
    name: "Eggs Benedict (Ham or Bacon)",
    price: "14.90",
    img: "https://i.imgur.com/EEZwTGj.jpg",
    description:
      "Poached eggs topped on toast with a choice of bacon or ham on top",
    category: "All Day Breakfast",
  },
  {
    name: "2Six Breakfast",
    price: "16.90",
    img: "https://i.imgur.com/8HX7RxK.jpg",
    description:
      "Scrambled eggs, bacon, ham, sausage, baked beans, seared tomato and toast",
    category: "All Day Breakfast",
    tags: "Chef Recommendation",
  },
  {
    name: "Ultimate Eggs Benedict",
    price: "17.90",
    img: "https://i.imgur.com/KtZXggc.jpg",
    description:
      "Poached eggs topped with hollandaise, avocado, beef patty, bacon, ham, toast and salad. ",
    category: "All Day Breakfast",
    tags: "Chef Recommendation",
  },
  {
    name: "Bolognese Pasta (Spaghetti or Fusilli)",
    price: "14.90",
    img: "https://i.imgur.com/EcwAcKB.jpg",
    description:
      "Pasta tossed in homemade beef and tomato sauce. An Italian classic. ",
    category: "Mains",
    tags: "Classic",
  },
  {
    name: "Carbonara Pasta (Spaghetti or Fusilli)",
    price: "14.90",
    img: "https://i.imgur.com/5nKlPDt.jpg",
    description: "Pasta tossed in egg yolk and cream sauce topped with bacon. ",
    category: "Mains",
  },
  {
    name: "BBQ Jumbo Beef Burger",
    price: "14.90",
    img: "https://i.imgur.com/XfFHiPF.jpg",
    description:
      "Classic large American burger with beef patty, lettuce, tomatoes and cheese.",
    category: "Mains",
  },
  {
    name: "Bulgogi Burger",
    price: "14.90",
    img: "https://i.imgur.com/jBUeQCu.jpg",
    description: "Japanese style beef patty in a classic burger.",
    category: "Mains",
  },
  {
    name: "Hawaiian Chicken Burger",
    price: "14.90",
    img: "https://i.imgur.com/3LoTqAG.jpg",
    description:
      "Burger with teriyaki marinated chicken, lettuce, tomatoes and mayonnaise sauce.",
    category: "Mains",
  },
  {
    name: "Teriyaki Chicken with Rice",
    price: "14.90",
    img: "https://i.imgur.com/mTVI7hp.jpg",
    description: "Teriyaki chicken cutlet served with steamed jasmine rice.",
    category: "Mains",
  },
  {
    name: "Japanese Hamburger Rice",
    price: "14.90",
    img: "https://i.imgur.com/s6khGMl.jpg",
    description: "Japanese style beef patty served with steamed jasmine rice. ",
    category: "Mains",
    tags: "Chef Recommendation",
  },
  {
    name: "Japanese Curry Omu Rice with Chicken Cutlet",
    price: "15.90",
    img: "https://i.imgur.com/9soG5oH.jpg",
    description:
      "Japanese curry rice topped with scrambled eggs and a classic chicken cutlet.",
    category: "Mains",
    tags: "All time favourite",
  },
  {
    name: "Gyudon",
    price: "15.90",
    img: "https://i.imgur.com/ZRYlN06.jpg",
    description:
      "Korean inspired marinated beef dish served with steamed jasmine rice. ",
    category: "Mains",
  },
  {
    name: "Kitsune Udon",
    price: "9.90",
    img: "https://i.imgur.com/sbMrHiU.jpg",
    description:
      "A vegetarian udon noodle soup topped with pieces of fried tofu.",
    category: "Mains",
  },
  {
    name: "Butter Lemon Baked Salmon",
    price: "17.90",
    img: "https://i.imgur.com/rGhZDQx.jpg",
    description:
      "Baked salmon seasoned with butter and lemon, served with steamed rice. ",
    category: "Mains",
  },
  {
    name: "Power Up! Chicken",
    price: "13.90",
    img: "https://i.imgur.com/HPOojQv.jpg",
    description:
      "Sous vide skinless chicken topped with hollandaise sauce, avocado, mashed potatoes and cherry tomatoes",
    category: "Mains",
  },
  {
    name: "Beef Lasagne",
    price: "13.90",
    img: "https://i.imgur.com/jDhnECD.jpg",
    description:
      "A classic Italian dish comprising sheets of pasta, cheese and minced beef, tossed in bolognese sauce.",
    category: "Mains",
  },
  {
    name: "Chicken Baked Rice",
    price: "13.90",
    img: "https://i.imgur.com/yRASi9x.jpg",
    description: "Baked cheese rice topped with chicken",
    category: "Mains",
  },
  {
    name: "Mushroom Macaroni",
    price: "13.90",
    img: "https://i.imgur.com/382WRET.jpg",
    description: "Mushroom in macaroni and cheese",
    category: "Mains",
  },
  {
    name: "American Beef Pie",
    price: "6.90",
    img: "https://i.imgur.com/HHTVbAM.jpg",
    description: "American inspired minced beef in puff pastry",
    category: "Pastries",
    tags: "Chef's Recommendation",
  },
  {
    name: "Chicken and Mushroom Pie",
    price: "6.90",
    img: "https://i.imgur.com/i3sKTqB.jpg",
    description: "Chicken and mushrooms wrapped in puff pastry",
    category: "Pastries",
  },
  {
    name: "Caesar Salad",
    price: "9.90",
    img: "https://i.imgur.com/LPGA4f6.jpg",
    description: "Mixed fresh salad greens with classic caesar sauce",
    category: "Sides",
    tags: "Healthy choice",
  },
  {
    name: "Avocado Tofu Salad",
    price: "10.90",
    img: "https://i.imgur.com/9OFsNvo.jpg",
    description:
      "A healthy blend of avocado and tofu with mixed fresh salad greens",
    category: "All Day Breakfast",
    tags: "Healthy choice",
  },
  {
    name: "Muffin (Banana Walnut/Chocolate)",
    price: "4.20",
    img: "https://i.imgur.com/vrYxhGg.jpg",
    description: "Muffin (Banana Walnut/Chocolate/Blueberry)",
    category: "Sides",
  },
  {
    name: "Nachos",
    price: "7.50",
    img: "https://i.imgur.com/Zs5ij0h.jpg",
    description: "Cheese and Mexican tortilla chips",
    category: "Sides",
  },
  {
    name: "Beef Slider",
    price: "13.90",
    img: "https://i.imgur.com/5N4Sjwg.jpg",
    description: "Classic beef club sandwich",
    category: "Sides",
  },
  {
    name: "Chicken Slider",
    price: "13.90",
    img: "https://i.imgur.com/PLuzndb.jpg",
    description: "Classic chicken club sandwich",
    category: "Sides",
  },
  {
    name: "Classic English Breakfast Tea",
    price: "6.90",
    img: "https://i.imgur.com/EHEqUUx.jpg",
    description: "Pure ceylon black tea",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Eternal Garden Tea",
    price: "6.90",
    img: "https://i.imgur.com/MMjgS7D.jpg",
    description: "Pure ceylon black tea, rose petals and rose flavour ",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Timeless Earl Grey",
    price: "6.90",
    img: "https://i.imgur.com/CyhOs1B.jpg",
    description:
      "Pure ceylon black tea with blue corn flower oil of bergamot and cream flavour ",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Fruitopia",
    price: "7.90",
    img: "https://i.imgur.com/Pzg72tC.jpg",
    description:
      "Pure ceylon black tea with a blend of fruit dices (apple, passion fruit, rapsberry, mango, soursop, orange and pineapple) and safflower",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Finest Darjeeling",
    price: "8.90",
    img: "https://i.imgur.com/4NdwGKd.jpg",
    description:
      "A classic Darjeeling Margaret's Hope with a beautiful muscatel flavour and aroma",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Black Tea Cocoa",
    price: "8.90",
    img: "https://i.imgur.com/Q6RfFuS.jpg",
    description:
      "A perfectly matched blend of black tea and cocoa, providing a unique flavour experience ",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Ever-Green Tea",
    price: "6.90",
    img: "https://i.imgur.com/Lvfv32j.jpg",
    description:
      "Ceylon hyson green tea from Sri Lanka's finest highland tea garden",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Lychee Fiesta",
    price: "7.90",
    img: "https://i.imgur.com/cx5n55F.jpg",
    description: "Chinese green tea with rose petals and lychee flavour",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Genmaicha",
    price: "7.90",
    img: "https://i.imgur.com/jIRjAkm.jpg",
    description:
      "Second flush tea leaves of Hamada tea. It gives a bright green colour with an aroma of roasted brown rice grains.",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Gyokuro",
    price: "8.90",
    img: "https://i.imgur.com/3yXT1og.jpg",
    description: "Shaded Japanese green tea from Yame. Fukuoka Prefecture.",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Chamomile",
    price: "6.90",
    img: "https://i.imgur.com/UKPoLfm.jpg",
    description: "Roman chamomile whole flowers from the Nile River, Egypt",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Ginger",
    price: "6.90",
    img: "https://i.imgur.com/sLbsPX1.jpg",
    description: "Dry ginger roots from Sri Lanka",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Lemongrass",
    price: "6.90",
    img: "https://i.imgur.com/XRHxAkH.jpg",
    description: "Pure lemongrass from Thailand",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Peppermint",
    price: "6.90",
    img: "https://i.imgur.com/dJnvj8u.jpg",
    description:
      "Dry-cut peppermint leaves (native to the Mediterranean region from North America)",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Anti-Stress",
    price: "7.90",
    img: "https://i.imgur.com/tj06JYJ.jpg",
    description:
      "Rooibos, chamomile, honeybush, lemon balm fennel, lemongrass flavour and ginseng root",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Blissful Berries",
    price: "7.90",
    img: "https://i.imgur.com/i6JKAB4.jpg",
    description:
      "A blend of hibiscus petals, apple, elderberries, rosechips, raspberry, blackberry and strawberry ",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Healing Garden",
    price: "7.90",
    img: "https://i.imgur.com/lYYLzlA.jpg",
    description:
      "Ginger, lemongrass, lemon peel, ginseng root, spearmint and liquorice ",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Peace of Mind",
    price: "7.90",
    img: "https://i.imgur.com/n0nT6kc.jpg",
    description:
      "Leon balm, orange blossom, sweet blackberry leaves, cardamom hull, fennel and anise",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Kalahari Rooibos",
    price: "8.90",
    img: "https://i.imgur.com/afyxjWe.jpg",
    description:
      "Go on safari with this taste intensive Rooibos blend with lemongrass and hibiscus flowers",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Alisan Oolong",
    price: "8.90",
    img: "https://i.imgur.com/SdaW1Op.jpg",
    description:
      "Lightly-oxidated Oolong tea from Taiwan's world-famous Alishan Mountains",
    category: "Beverages",
    tags: "Tea",
  },
  {
    name: "Capuccino",
    price: "8.90",
    img: "https://i.imgur.com/DFgPToq.jpg",
    description: "Capuccino",
    category: "Beverages",
    tags: "Coffee",
  },
];
